name: store_sales_environment
dependencies:
  - python=3.10
  - pip:
    - pandas==1.3.5
    - xgboost==3.0.0
    - azureml-defaults==1.60.0
    - mlflow==2.21.3
channels:
  - conda-forge
  - defaults